version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootrroot
      MYSQL_DATABASE: microservice-db
      MYSQL_USER: programmer
      MYSQL_PASSWORD: progpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
